### ISSUE TITLE
fix: e2e tests cannot run

### ISSUE THREAD

**Issue by rolandjitsu** [rolandjitsu/angular-lab#63]
Right now e2e tests cannot run, also reported in [#4808](https://github.com/angular/angular-cli/issues/4808).

**Comment by rodrigopandini** [comment]
@rolandjitsu Try to move the `require('ts-node').register({ project: 'e2e' });` code from `beforeLaunch` to `onPrepare` function. It's worked for me.
Check here: https://github.com/angular/angular-cli/issues/975

**Comment by rolandjitsu** [comment]
Thanks @rodrigopandini, that seems to work.
